name: Build Project

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build
        run: |
          sudo apt-get -y install cmake
          cmake .
          make
