name: Build

on: [push, pull_request]

jobs:

  build-on-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install CMake
        run: sudo apt-get -y install cmake

      - name: Build Project
        run: |
          cmake .
          make

    build-on-windows:
      runs-on: windows-latest

      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2

        - name: Install CMake
          run: choco install cmake

        - name: Build Project
          run: |
            cmake .
            make
